blueprint:
  name: Mila reset when idle
  domain: automation
  input:
    low_amp_limit:
      name: Lower bound consumpation (amps)
      default: 0.1
      selector:
        number:
          min: 0
          max: 15
          step: 0.1
          unit_of_measurement: Amps
    low_power_wait:
      name: Wait time
      description: The time to wait after power drops below threshold.
      default: 45
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: minutes
    power_entity:
      name: Power
      selector:
        device_class: current
    switch_entity:
      name: Switch
      selector:
        entity:
          domain: switch

mode: restart
max_exceeded: silent

trigger:
  - type: current
    platform: device
    entity_id: !input power_entity
    domain: sensor
    below: !input low_amp_limit
    for:
      hours: 0
      minutes: !input low_power_wait
      seconds: 0
condition: []
action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: !input switch_entity
  - wait_for_trigger:
    platform: state
    entity_id: !input switch_entity
    from: "on"
    to: "off"
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
  - service: switch.turn_on
    data: {}
    target:
      entity_id: !input switch_entity